apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: lombre/udagram-api-feed:v3
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secrets
        volumeMounts:
          - mountPath:  "/root/.aws/"
            name: aws-creds
      volumes:
        - name: aws-creds
          configMap:
            name: aws-creds